import { Activity, Award, Box, Briefcase, Brush, Camera, Car, ChartNoAxesCombined, Contact, CreditCard, DollarSign, Drum, Fuel, GraduationCap, HandCoins, Heart, Home, Mic, NotebookPen, Phone, PiggyBank, Plug, Scissors, Shirt, ShoppingCart, ShowerHead, Star, Tag, Truck, TvMinimalPlay, User, Utensils, Wifi, Wrench, Zap } from "lucide-react";

export const IconCategory = [
    { name: 'Home', icon: Home },
    { name: 'Car', icon: Car },
    { name: 'Truck', icon: Truck },
    { name: 'Heart', icon: Heart },
    { name: 'Star', icon: Star },
    { name: 'Tag', icon: Tag },
    { name: 'NotebookPen', icon: NotebookPen },
    { name: 'Utensils', icon:Utensils},
    { name: 'HandCoins', icon: HandCoins },
    { name: 'Briefcase', icon: Briefcase },
    { name: 'GraduationCap', icon: GraduationCap },
    { name: 'ShoppingCart', icon: ShoppingCart },
    { name: 'CreditCard', icon: CreditCard },
    { name: 'DollarSign', icon: DollarSign },
    { name: 'PiggyBank', icon: PiggyBank },
    { name: 'TvMinimalPlay', icon: TvMinimalPlay },
    { name: 'Shirt', icon: Shirt },
    { name: 'Activity', icon: Activity },
    { name: 'Box', icon: Box },
    { name: 'Camera', icon: Camera },
    { name: 'Drum', icon: Drum },
    { name: 'Fuel', icon: Fuel },
    { name: 'Phone', icon: Phone },
    { name: 'Plug', icon: Plug },
    { name: 'Wifi', icon: Wifi },
    { name: 'User', icon: User },
    { name: 'Contact', icon: Contact },
    { name: 'Zap', icon: Zap },
    { name: 'ShowerHead', icon: ShowerHead },
    { name: 'Scissors', icon: Scissors },
    { name: 'Wrench', icon: Wrench },
    { name: 'Mic', icon: Mic },
    { name: 'Brush', icon: Brush },
    { name: 'Award', icon: Award },
    { name: 'ChartNoAxesCombined', icon: ChartNoAxesCombined },
    
];